#turn on command echoing 
set -x

#set source script
source dispatch_variables.sh

echo $BASELINE_VARIANT
echo $VARIANT_1
echo $VARIANT_2
echo $VARIANT_3
echo $CC
echo $CFLAGS

#set reference names
COMPUTE_NAME_REF="baseline"
DISTRIBUTED_ALLOCATE_NAME_REF="baseline_distribute"
DISTRIBUTED_FREE_NAME_REF="baseline_free"
DISTRIBUTED_DATA_NAME_REF="baseline_distribute_data"
COLLECT_DATA_NAME_REF="baseline_collect"

#set test names
COMPUTE_NAME_TST="test"
DISTRIBUTED_ALLOCATE_NAME_TST="test_allocate"
DISTRIBUTED_FREE_NAME_TST="test_free"
DISTRIBUTED_DATA_NAME_TST="test_dist"
COLLECT_DATA_NAME_TST="test_collect_data"


VERIFIER_RIG="verifier_op.c"

#BUILD VERIFICATION TEST
${CC} -std=c99 -c \
    -DCOMPUTE_OP_REF=${COMPUTE_NAME_REF} \
    -DDISTRIBUTE_ALLOCATION_REF=${DISTRIBUTED_ALLOCATE_NAME_REF} \
    -DDISTRIBUTE_DATA_REF=${DISTRIBUTED_DATA_NAME_REF} \
    -DCOLLECTION_REF=${COLLECT_DATA_NAME_REF} \
    -DFREE_MEMORY_REF=${DISTRIBUTED_FREE_NAME_REF} \
    -DCOMPUTE_OP_TEST=${COMPUTE_NAME_TST} \
    -DDISTRIBUTE_ALLOCATION_TEST=${DISTRIBUTED_ALLOCATE_NAME_TST} \
    -DDISTRIBUTE_DATA_TEST=${DISTRIBUTED_DATA_NAME_TST} \
    -DCOLLECTION_TEST=${COLLECT_DATA_NAME_TST} \
    -DFREE_MEMORY_TEST=${DISTRIBUTED_FREE_NAME_TST} \
    ${VERIFIER_RIG} -o ${VERIFIER_RIG}.o

#BUILD BASELINE VARIANT
${CC} -std=c99 -c\
    -DCOMPUTE_OP=${COMPUTE_NAME_REF} \
    -DDISTRIBUTE_ALLOCATION=${DISTRIBUTED_ALLOCATE_NAME_REF} \
    -DFREE_MEMORY=${DISTRIBUTED_FREE_NAME_REF} \
    -DDISTRIBUTE_DATA=${DISTRIBUTED_DATA_NAME_REF} \
    -DCOLLECTION=${COLLECT_DATA_NAME_REF} \
    ${BASELINE_VARIANT} -o ${BASELINE_VARIANT}.ref.o

#BUILD VARIANT 1
${CC} -std=c99 -c\
    -DCOMPUTE_OP=${COMPUTE_NAME_TST} \
    -DDISTRIBUTE_ALLOCATION=${DISTRIBUTED_ALLOCATE_NAME_TST} \
    -DFREE_MEMORY=${DISTRIBUTED_FREE_NAME_TST} \
    -DDISTRIBUTE_DATA=${DISTRIBUTED_DATA_NAME_TST} \
    -DCOLLECTION=${COLLECT_DATA_NAME_TST} \
    ${VARIANT_1} -o ${VARIANT_1}.o

#BUILD VARIANT 2
${CC} -std=c99 -c\
    -DCOMPUTE_OP=${COMPUTE_NAME_TST} \
    -DDISTRIBUTE_ALLOCATION=${DISTRIBUTED_ALLOCATE_NAME_TST} \
    -DFREE_MEMORY=${DISTRIBUTED_FREE_NAME_TST} \
    -DDISTRIBUTE_DATA=${DISTRIBUTED_DATA_NAME_TST} \
    -DCOLLECTION=${COLLECT_DATA_NAME_TST} \
    ${VARIANT_2} -o ${VARIANT_2}.o

#BUILD VARIANT 3
${CC} -std=c99 -c\
    -DCOMPUTE_OP=${COMPUTE_NAME_TST} \
    -DDISTRIBUTE_ALLOCATION=${DISTRIBUTED_ALLOCATE_NAME_TST} \
    -DFREE_MEMORY=${DISTRIBUTED_FREE_NAME_TST} \
    -DDISTRIBUTE_DATA=${DISTRIBUTED_DATA_NAME_TST} \
    -DCOLLECTION=${COLLECT_DATA_NAME_TST} \
    ${VARIANT_3} -o ${VARIANT_3}.o

#BUILD THE VERIFIER EXECUTABLES
${CC} ${CFLAGS} -std=c99 ${BASELINE_VARIANT}.ref.o ${VERIFIER_RIG}.o ${VARIANT_1}.o -o ./run_verifier_variant01.x
${CC} ${CFLAGS} -std=c99 ${BASELINE_VARIANT}.ref.o ${VERIFIER_RIG}.o ${VARIANT_2}.o -o ./run_verifier_variant02.x
${CC} ${CFLAGS} -std=c99 ${BASELINE_VARIANT}.ref.o ${VERIFIER_RIG}.o ${VARIANT_3}.o -o ./run_verifier_variant03.x

echo "Verifier executables build complete"

#turn off command echoing
set +x