#turn on command echoing
set -x

source dispatch_variables.sh

#echo from build_test_op.sh
echo $BASELINE_VARIANT
echo $VARIANT_1
echo $VARIANT_2
echo $VARIANT_3
echo $CC
echo $CFLAGS

COMPUTE_NAME_REF="baseline"
DISTRIBUTED_ALLOCATE_NAME_REF="baseline_allocate"
DISTRIBUTED_FREE_NAME_REF="baseline_free"
DISTRIBUTED_DATA_NAME_REF="baseline_dist"
COLLECT_DATA_NAME_REF="baseline_collect_data"

COMPUTE_NAME_TST="test"
DISTRIBUTED_ALLOCATE_NAME_TST="test_allocate"
DISTRIBUTED_FREE_NAME_TST="test_free"
DISTRIBUTED_DATA_NAME_TST="test_dist"
COLLECT_DATA_NAME_TST="test_collect_data"

TEST_RIG="verify_op.c"

#BUILD VERIFICATION TEST
${CC} -std=c99 -c \
    -DCOMPUTE_NAME=${COMPUTE_NAME_REF} \
    -DDISTRIBUTED_ALLOCATE_NAME=${DISTRIBUTED_ALLOCATE_NAME_REF} \
    -DDISTRIBUTED_FREE_NAME=${DISTRIBUTED_FREE_NAME_REF} \
    -DDISTRIBUTED_DATA_NAME=${DISTRIBUTED_DATA_NAME_REF} \
    -DCOLLECT_DATA_NAME=${COLLECT_DATA_NAME_REF} \
    -DCOMPUTE_NAME_TST=${COMPUTE_NAME_TST} \
    -DDISTRIBUTED_ALLOCATE_NAME_TST=${DISTRIBUTED_ALLOCATE_NAME_TST} \
    -DDISTRIBUTED_FREE_NAME_TST=${DISTRIBUTED_FREE_NAME_TST} \
    -DDISTRIBUTED_DATA_NAME_TST=${DISTRIBUTED_DATA_NAME_TST} \
    -DCOLLECT_DATA_NAME_TST=${COLLECT_DATA_NAME_TST} \
    ${TEST_RIG} -o ${TEST_RIG}.o

#BUILD REFERENCE BASELINE 
${CC} -std=c99 -c\
    -DCOMPUTE_NAME=${COMPUTE_NAME_REF} \
    -DDISTRIBUTED_ALLOCATE_NAME=${DISTRIBUTED_ALLOCATE_NAME_REF} \
    -DDISTRIBUTED_FREE_NAME=${DISTRIBUTED_FREE_NAME_REF} \
    -DDISTRIBUTED_DATA_NAME=${DISTRIBUTED_DATA_NAME_REF} \
    -DCOLLECT_DATA_NAME=${COLLECT_DATA_NAME_REF} \
    ${BASELINE_VARIANT} -o ${BASELINE_VARIANT}.ref.o


#BUILD VARIANT 1
${CC} -std=c99 -c\
    -DCOMPUTE_NAME=${COMPUTE_NAME_TST} \
    -DDISTRIBUTED_ALLOCATE_NAME=${DISTRIBUTED_ALLOCATE_NAME_TST} \
    -DDISTRIBUTED_FREE_NAME=${DISTRIBUTED_FREE_NAME_TST} \
    -DDISTRIBUTED_DATA_NAME=${DISTRIBUTED_DATA_NAME_TST} \
    -DCOLLECT_DATA_NAME=${COLLECT_DATA_NAME_TST} \
    ${VARIANT_1} -o ${VARIANT_1}.o

#BUILD VARIANT 2
${CC} -std=c99 -c\
    -DCOMPUTE_NAME=${COMPUTE_NAME_TST} \
    -DDISTRIBUTED_ALLOCATE_NAME=${DISTRIBUTED_ALLOCATE_NAME_TST} \
    -DDISTRIBUTED_FREE_NAME=${DISTRIBUTED_FREE_NAME_TST} \
    -DDISTRIBUTED_DATA_NAME=${DISTRIBUTED_DATA_NAME_TST} \
    -DCOLLECT_DATA_NAME=${COLLECT_DATA_NAME_TST} \
    ${VARIANT_2} -o ${VARIANT_2}.o

#BUILD VARIANT 3
${CC} -std=c99 -c\
    -DCOMPUTE_NAME=${COMPUTE_NAME_TST} \
    -DDISTRIBUTED_ALLOCATE_NAME=${DISTRIBUTED_ALLOCATE_NAME_TST} \
    -DDISTRIBUTED_FREE_NAME=${DISTRIBUTED_FREE_NAME_TST} \
    -DDISTRIBUTED_DATA_NAME=${DISTRIBUTED_DATA_NAME_TST} \
    -DCOLLECT_DATA_NAME=${COLLECT_DATA_NAME_TST} \
    ${VARIANT_3} -o ${VARIANT_3}.o

#Build the test executables
${CC} ${CFLAGS} ${TEST_RIG}.o ${BASELINE_VARIANT}.ref.o ${VARIANT_1}.o -o ./run_test_variant01.x
${CC} ${CFLAGS} ${TEST_RIG}.o ${BASELINE_VARIANT}.ref.o ${VARIANT_2}.o -o ./run_test_variant02.x
${CC} ${CFLAGS} ${TEST_RIG}.o ${BASELINE_VARIANT}.ref.o ${VARIANT_3}.o -o ./run_test_variant03.x

echo "Build Test: complete"